name: Validate quickstarts

on:
  workflow_run:
    workflows: ["Validation Gate"]
    types:
      - completed

jobs:
  print:
    name: hello
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/debug-action@v2

  ensure-schema-compliance:
    name: Ensure schema compliance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: 'refs/pull/${{ github.event.inputs.pull_request_number }}/merge'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Validate pr quickstart files
        id: testing_me
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NR_API_URL: "https://api.newrelic.com/graphql"
          NR_API_TOKEN: ${{ secrets.NR_API_TOKEN }}
        run: |
          echo "Hello world"
      
      - name: Add commit status
        if: always()
        run: |
          export COMMIT_SHA=$(echo '${{ toJSON(github.event) }}' | jq '.workflow_run.head_commit.id' | tr -d '"')
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/statuses/$COMMIT_SHA \
            -d '{"description":"Ensure schema compliance","state":"${{ steps.testing_me.outcome }}" }'

  ensure-quickstart-names-ids-are-unique:
    name: Ensure quickstart names and ids are unique
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: 'pull/${{ github.event.inputs.pull_request_number }}/head'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Check for unique names and ids
        id: testing_me
        run: |
          exit 1

      - name: Add commit status
        if: always()
        run: |
          export COMMIT_SHA=$(echo '${{ toJSON(github.event) }}' | jq '.workflow_run.head_commit.id' | tr -d '"')
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/statuses/$COMMIT_SHA \
            -d '{"description":"Ensure quickstart names are unique", "state":"${{ steps.testing_me.outcome }}" }'